title: zetc0de
description: My Personal Blog
author: Havidzc0de
logo: /static/img/avatar.png
github: https://github.com/zetc0de
about: Coretan Kecilku... ^_^ 

baseurl: "https://zetc0de.github.io"
url: "https://zetc0de.github.io"

comments: true
layout: default 

allowsearch: true

disqus_shortname: zetc0de
google_analytics: UA-117516737-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
