title: Havidzc0de
description: My Personal Blog
author: Havidzc0de
logo: /static/img/avatar.png
github: https://github.com/havidzc0de
about: Coretan Kecilku... ^_^ 

baseurl: "https://havidzc0de.github.io"
url: "https://havidzc0de.github.io"

comments: true
layout: default 

allowsearch: true

disqus_shortname: havidzc0de
google_analytics: UA-117516737-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
